dir_work: "/data/home/pengjia/Project_Human_DATA/reNBT/03_benchmark_test/release_regions/"


software:
  "bedtools": "/data/home/pengjia/miniconda3/envs/default/bin/bedtools"
  "tabix": "/data/home/pengjia/miniconda3/envs/default/bin/tabix"
  "bgzip": "/data/home/pengjia/miniconda3/envs/default/bin/bgzip"
  "gzip": "gzip"
  "hap_eval": "/data/home/pengjia/miniconda3/envs/happy/bin/hap.py"
  "truvari": "/data/home/pengjia/miniconda3/envs/truvari/bin/truvari"


regions:
  "GRCh38":
    "TierAll": "/data/home/pengjia/Project_Human_DATA/reNBT/02_variants/release/ChineseQuartet.twin.germline.GRCh38.benchmark_region.v2.0.bed"
    "Tier1_SV": "/data/home/pengjia/Project_Human_DATA/reNBT/02_variants/release/ChineseQuartet.twin.germline.GRCh38.SV_Tier1.v2.0.bed"
    "Tier1_Small": "/data/home/pengjia/Project_Human_DATA/reNBT/02_variants/release/ChineseQuartet.twin.germline.GRCh38.small_Tier1.v2.0.bed"
    "SD": "/data/home/pengjia/Project_Human_DATA/reNBT/v2.0_release/Regions/GRCh38_SegmentalDuplication.bed.gz"
    "SR": "/data/home/pengjia/Project_Human_DATA/reNBT/v2.0_release/Regions/GRCh38_SimpleRepeat.bed.gz"
    "VNTR": "/data/home/pengjia/Project_Human_DATA/reNBT/v2.0_release/Regions/GRCh38_VNTR.bed.gz"
    "STR": "/data/home/pengjia/Project_Human_DATA/reNBT/v2.0_release/Regions/GRCh38_STR_MSIsensor.bed.gz"
    "RM": "/data/home/pengjia/Project_Human_DATA/reNBT/v2.0_release/Regions/GRCh38_RepeatMask.bed.gz"
regions_pattern:
  "GRCh38":
    - "TierAll"
    - "Tier1_SV"
    - "Tier1_Small"
    - "TierAll_include_SD"
    - "TierAll_exclude_Tier1_Small"
    - "TierAll_exclude_Tier1_SV"
    - "TierAll_exclude_SD"
    - "TierAll_include_STR"
    - "TierAll_exclude_STR"
    - "TierAll_include_VNTR"
    - "TierAll_exclude_VNTR"
    - "TierAll_include_SR"
    - "TierAll_exclude_SR"
    - "TierAll_include_RM"
    - "TierAll_exclude_RM"
    - "Tier1_SV_include_SD"
    - "Tier1_SV_exclude_SD"
    - "Tier1_SV_include_STR"
    - "Tier1_SV_exclude_STR"
    - "Tier1_SV_include_VNTR"
    - "Tier1_SV_exclude_VNTR"
    - "Tier1_SV_include_SR"
    - "Tier1_SV_exclude_SR"
    - "Tier1_SV_include_RM"
    - "Tier1_SV_exclude_RM"
    - "Tier1_Small_exclude_SD"
    - "Tier1_Small_include_STR"
    - "Tier1_Small_exclude_STR"
    - "Tier1_Small_exclude_VNTR"
    - "Tier1_Small_exclude_SR"
    - "Tier1_Small_include_RM"
    - "Tier1_Small_exclude_RM"